version: "3.9"
services:
  web:
    command: uvicorn app.main:app --host 0.0.0.0
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
